Section "InputClass"
    Identifier "touchscreen"
    MatchIsTouchscreen "on"
    Driver "libinput"
    Option "ScrollMethod" "twofinger"
    Option "NaturalScrolling" "true"
    Option "Tapping" "on"
EndSection
